### ISSUE TITLE
There are RT issues

### ISSUE THREAD

**Issue by eserte** [derf/Travel-Status-DE-IRIS#10]
Please see https://rt.cpan.org/Dist/Display.html?Name=Travel-Status-DE-IRIS

**Comment by derf** [comment]
Oh dear. I got notified by mail about those and then forgot about them when making today's release.

Thanks for the reminder!

**Comment by eserte** [comment]
Still this issue is open. On some of my smokers I see
```
Can't locate object method "distance_km" via package "GIS::Distance" at /usr/perl5.16.3t/lib/site_perl/5.16.3/Geo/Distance.pm line 252.
```
probably if older Geo::Distance and/or GIS::Distance is installed.
