### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by wopfel** [derf/Travel-Status-DE-IRIS#21]
Hi,
I installed the .deb package on Ubuntu 20.10 and it seems there are Perl packages which are not automatically installed. 

```shell
$ wget https://lib.finalrewind.org/deb/libtravel-status-de-iris-perl_dev_all.deb
$ sudo apt install ./libtravel-status-de-iris-perl_dev_all.deb
...
$ db-iris
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.3 /usr/local/share/perl/5.30.3 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl) at /usr/bin/db-iris line 15.
BEGIN failed--compilation aborted at /usr/bin/db-iris line 15.
```

It's the same error when:
- using libtravel-status-de-iris-perl_**latest**_all.deb
- running on Ubuntu 20.04.1 LTS
- using libtravel-status-de-iris-perl_**1.45-1**_all.deb
- using version 1.46-1 on Debian GNU/Linux 10 (buster)

I had to install some packages manually:
- libjson-perl
- libcache-perl

After both packages have been installed, the `db-iris` command works just fine.

Could we add those packages to a dependency list so apt installs them automatically?

Kind regards,
Bernd

**Comment by derf** [comment]
Indeed. Fixed, thanks! dev_all.deb is just updating, latest will follow later.
