### ISSUE TITLE
wget of .deb package results in 502 bad gateway

### ISSUE THREAD

**Issue by wopfel** [derf/Travel-Status-DE-IRIS#23]
Hi Daniel,
First of all, happy new year :)

When I try to download the .deb packages, as mentioned in the README's section [Nightly Builds for Debian](https://github.com/derf/Travel-Status-DE-IRIS/blob/master/README.md#nightly-builds-for-debian), every web link results in a 502 bad gateway.

- https://lib.finalrewind.org/deb
- https://lib.finalrewind.org/deb/libtravel-status-de-iris-perl_latest_all.deb
- https://lib.finalrewind.org/deb/libtravel-status-de-iris-perl_dev_all.deb

Did they move to another location?

Kind regards,
Bernd

**Comment by derf** [comment]
Hi! A happy new year to you as well.

That was a network configuration issue. I have resolved it and the links are working again, thanks for pointing it out.
