### ISSUE TITLE
wget of .deb package results in 504 Gateway Time-out

### ISSUE THREAD

**Issue by wopfel** [derf/Travel-Status-DE-IRIS#25]
Hi Daniel,
When I'm trying to download the latest .deb package, I get the following error:

```
$ wget https://lib.finalrewind.org/deb/libtravel-status-de-iris-perl_latest_all.deb
...
Connecting to lib.finalrewind.org (lib.finalrewind.org)|51.15.37.212|:443... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
```

Same result when trying `wget 'https://arclight.derf0.net/deb/libtravel-status-de-iris-perl_1.60-1_all.deb'`.

Kind regards,
Bernd

**Comment by derf** [comment]
Fixed, thanks for notifying me. Somehow those URLs haven't made it into my monitoring yet…

**Comment by wopfel** [comment]
Thank you very much! 😃

**Comment by d-bieber** [comment]
Looks like it is broken again. Same issue, unfortunately
