### ISSUE TITLE
503 Service Temporarily Unavailable / 502 Bad Gateway

### ISSUE THREAD

**Issue by LaCruz75** [derf/Travel-Status-DE-IRIS#27]
I got since some days the error "503" over db-iris with my local DBF installation.
Manually I tried:

https://iris.noncd.db.de/iris-tts/timetable/station/Bochum-Hamme

Same issue with browser.
Is there an new URL (iris_base)?

**Comment by LaCruz75** [comment]
https://twitter.com/dbopendata

Maybe log4shell issue - but why https://dbf.finalrewind.org seems to work?

**Comment by derf** [comment]
DBF used a (non-public) fall-back IRIS instance during the log4j downtime. Things should be back to normal for self-hosted installations now.
