### ISSUE TITLE
missing/new station: 'Frick'

### ISSUE THREAD

**Issue by derklaro** [derf/Travel-Status-DE-IRIS#31]
Found a new station (registered 25.05.2024) registered in IRIS: 'Frick'. 

Eva: 8500305
DS100: XSFRK
Longitude: 8.01268, Latitude: 47.507164 (according to RIS::Stations)
IRIS-URL: https://iris.noncd.db.de/iris-tts/timetable/station/Frick/

For example used by IC 60402 found in plan of cologne main station: https://iris.noncd.db.de/iris-tts/timetable/plan/8000207/240527/06

Wanted to register it myself into the stations json, but my nonexistent perl knowledge did hinder me 😄

**Comment by derklaro** [comment]
Also just found 'Zapresic' (registered 25.05.2024):

Eva: 7800061
DS100: XRZP
Longitude: 15.8131871, Latitude: 45.8444947 (according to RIS::Stations)
IRIS-URL: https://iris.noncd.db.de/iris-tts/timetable/station/Zapresic/

(hope it's ok to just throw this in here as well)

**Comment by derf** [comment]
That's ok, thanks for notifying me about both! I haven't spent much time on the IRIS backend as it will likely be decommissioned in the near future.

I'll push a release that includes these two stations (and a bunch more found by my maintenance script) later this week.

**Comment by derklaro** [comment]
Ok, there seem to be a lot more, these are the ones I found so far (all at stuttgart main station), will keep an eye out for more in the next days 😄 :

Name: Borovnica
Eva: 7900080
DS100: XZBO
Longitude: 14.3679717, Latitude: 45.9213192 (according to RIS::Stations)
IRIS-URL: https://iris.noncd.db.de/iris-tts/timetable/station/Borovnica

Name: Postojna
Eva: 7900012
DS100: XZPJ
Longitude: 14.2214694, Latitude: 45.7731017 (according to RIS::Stations)
IRIS-URL: https://iris.noncd.db.de/iris-tts/timetable/station/Postojna

Name: Pivka
Eva: 7900011
DS100: XZPV
Longitude: 14.1913756, Latitude: 45.6752532 (according to RIS::Stations)
IRIS-URL: https://iris.noncd.db.de/iris-tts/timetable/station/Pivka

Name: Ilirska Bistrica
Eva: 7900029
DS100: XZIB
Longitude: 14.2360365, Latitude: 45.5692757 (according to RIS::Stations)
IRIS-URL: https://iris.noncd.db.de/iris-tts/timetable/station/Ilirska%20Bistrica

Name: Sapjane
Eva: 7800067
DS100: XRSJ
Longitude: 14.2443518, Latitude: 45.4770352 (according to RIS::Stations)
IRIS-URL: https://iris.noncd.db.de/iris-tts/timetable/station/Sapjane

Name: Opatija Matulji
Eva: 7800002
DS100: XROM
Longitude: 14.3209803, Latitude: 45.3647017 (according to RIS::Stations)
IRIS-URL: https://iris.noncd.db.de/iris-tts/timetable/station/Opatija%20Matulji

Name: Rijeka
Eva: 7800013
DS100: XRR
Longitude: 14.4303372, Latitude: 45.3301347 (according to RIS::Stations)
IRIS-URL: https://iris.noncd.db.de/iris-tts/timetable/station/Rijeka
