### ISSUE TITLE
Wolfenbüttel shows 

### ISSUE THREAD

**Issue by joerggollnick** [derf/Travel-Status-DE-IRIS#6]
Summary: Stations.pm - Data for HWOL Wolfenbüttel  should be HWOH Wolfenbüttel 

Wolfenbüttel hat zwei Betriebsstellen HWOL und HWOH.
In den Daten der DB steht:
``
HWOH;Wolfenbüttel Hp;Wolfenbüttel Hp;Hp;;DE21258;0080;2;20081214;;805168;J;N
HWOL;Wolfenbüttel;Wolfenbüttel;Bf;;DE21257;0080;2;20081214;;133447;J;N
``
Züge halten nur in HWOH, der aber für Reisende als Wolfenbüttel gekennzeichnet ist.
Ich habe für mich HWOL durch HWOH ersetzt und schon wird auch Wolfenbüttel angezeigt.

Die beste Lösung für das Modul kann ich nicht beurteilen, die ID 8000255 und die Koordinaten stimmen für HWOH. Der Name differiert ja.

**Comment by derf** [comment]
Das ist hier auch die beste Lösung, Kern des Moduls ist ja ein nutzbarer Abfahrtsmonitor und nicht eine 100% korrekte Betriebsstellenliste. Danke für den Hinweis!
