### ISSUE TITLE
message code 4

### ISSUE THREAD

**Issue by ip138** [derf/Travel-Status-DE-IRIS#7]
The message code is "Kurzfristiger Personalausfall" regarding to the DB Navigator App.

**Comment by derf** [comment]
Oooh, interesting.

Do you have a link / train ID so I can verify it?

**Comment by derf** [comment]
Ah, so I can just look out for the Westfranken-/Hohenlohebahn trains mentioned on https://www.bahn.de/p/view/service/aktuell/index.shtml, neat. I'll see that I can verify it tomorrow (just to be sure), thanks for the hint :)
